# Generated by Django 5.2.6 on 2025-09-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_interested',
            field=models.CharField(max_length=200, verbose_name='Course/Program Interested In'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_college',
            field=models.CharField(max_length=200, verbose_name='Current/Last School or College'),
        ),
    ]
