# Generated by Django 5.2.6 on 2025-09-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_course_interested_alter_student_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
